# Generated by Django 4.1 on 2022-08-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participants',
            new_name='members',
        ),
    ]
